### ISSUE TITLE
mini-core

### ISSUE THREAD

**Issue by lecheng-lc** [llf137224350/mini-core-todo-list#1]
[mini-core](http://www.uicoder.cn/mini_core_docs/)  大佬，没开源啊  想研究下源码   😊

**Comment by llf137224350** [comment]
不好意思，这个目前还没计划好开源




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月17日(星期二) 上午10:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [llf137224350/mini-core-todo-list] mini-core (Issue #1)





 
mini-core  没开源  想研究下源码

**Comment by llf137224350** [comment]
开源了 可以试试



发自我的iPhone


------------------ Original ------------------
From: leCheng ***@***.***&gt;
Date: Tue,May 17,2022 10:38 AM
To: llf137224350/mini-core-todo-list ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [llf137224350/mini-core-todo-list] mini-core (Issue #1)





 
mini-core  没开源  想研究下源码
